version: '3'

services:
  employees-app-mariadb:
    image: mariadb
    expose:
      - 3306
    ports:
      - 3308:3306
    environment:
      MYSQL_DATABASE: employees
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes' # aposztrófok nélkül boolean true-ként értelmezi
      MYSQL_USER: employees
      MYSQL_PASSWORD: employees

  employees-app:
    image: employees
    depends_on:
      - employees-app-mariadb
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:mariadb://employees-app-mariadb:3306/employees'
      SPRING_DATASOURCE_USERNAME: 'employees'
      SPRING_DATASOURCE_PASSWORD: 'employees'
    entrypoint: ["/opt/wait/wait-for-it.sh", "-t", "120", "employees-app-mariadb:3306", "--", "java", "-jar", "app.jar"]
    expose:
      - 8080
    volumes:
    - ./wait:/opt/wait
    scale: 2

  employees-web:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - employees-app
    ports:
      - "80:80"

  employees-newman:
    image: postman/newman:5-ubuntu
    volumes:
    - ./postman:/etc/newman
    - ./wait:/opt/wait
    entrypoint: ["/opt/wait/wait-for-it.sh", "-t", "120", "employees-app-e2e-employees-app-1:8080", "--", "newman", "run", 'Employees.postman_collection.json', '-e', 'dev.postman_environment.json']
    depends_on:
      - employees-it-app
